name: BlockCityTycoonMine
version: '${project.version}'
main: me.darkmun.blockcitytycoonmine.BlockCityTycoonMine
authors: [ Darkmun ]
depend: [ProtocolLib, PacketWrapper, Vault]
commands:
  stonespawnchance:
    description: Изменяет шанс спавна камней
  updatepickaxe:
    description: Меняет кирку или добавляет некоторые энчанты
    aliases:
      - up